### PR TITLE
Created a Chicago_EDT folder to store custom footprints. Created DIP60.fp.

### PR DESCRIPTION
**Pull request by sabinoj**
Created a Chicago_EDT folder for the footprints that are custom to only us due to certain usage. Also created a sixty pin dual inline package footprint to simplify IGVC backplane design.

### CODE REVIEW

**Comment by sabinoj** [comment]
As far as I can tell everything checks out, but can someone verify that it all works correctly?

**Comment by l0g1x** [comment]
Can you classify the footprint into their respective categories instead? No point in creating a edt folder when its a edt repo in the first place

Krystian Gebis
University of Illinois - Chicago
Chicago EDT - Robotics (Software)
Undergraduate Computer Engineering

**Comment by sabinoj** [comment]
The reason that there is an EDT folder is because it does not fall under any manufacturer and only has limited application within our own projects.

**Comment by l0g1x** [comment]
name it custom or custom_footprints then

**Comment by sabinoj** [comment]
Take into consideration someone pulling down another custom repository that is not sorted or organized, this can cause a lot of confusion.

**Comment by sabinoj** [comment]
I think we should get a third opinion.

**Comment by sabinoj** [comment]
Due to the application of this footprint this pull request will be merged.

**Pull request merged**
